"""Emit the soft arm's Drake model from `params.py`, so the two cannot drift.

The generated file is committed alongside this generator, and a test regenerates it and
asserts byte-equality -- the discipline the repo already runs on the hardened scene YAMLs
("Edit the legacy file and re-derive; do not hand-edit the two out of step").

WHY FLOATING BODIES AND NOT A JOINT CHAIN.  A constant-strain segment is not a Drake
joint, so the sub-link poses have to be written into the plant from outside either way.
Given that, a body with no inboard joint -- which SDFormat makes a quaternion floating
body, 7 positions -- is strictly better than a 3-prismatic + 3-revolute chain through
dummy links:

  * no gimbal lock, so the RPY pitch singularity never arises;
  * one body per sub-link instead of six;
  * the plant's position limits are +-inf, so a sampler that draws uniformly over plant
    limits fails LOUDLY with nan instead of quietly producing nonsense. That sampler is
    exactly what the existing benchmark scripts do, and the soft-arm script has to
    replace it.

WHY SPHERES AND NOT CAPSULES.  Measured, and it is not a preference. Drake's proximity
engine hangs on this model's capsules -- a 6-body, ZERO-candidate-pair capsule model did
not complete a single `MinimumDistanceLowerBoundConstraint` evaluation in minutes, while
the identical sphere model evaluates in microseconds. The same sphere model costs 0.03-0.06
ms per AutoDiffXd evaluation with 30 derivative directions on the full 4x6 arm, against the
flow's ~17 ms, so collision is not this robot's bottleneck. The tree's own iiwa collision
model is `iiwa14_spheres_cylinders_collision.urdf`, so spheres are also the house style.

THE SPHERE UNION *IS* THE ROBOT.  It is declared geometry, not an approximation of a swept
rod, so the collision constraint is exact on the robot as defined rather than approximate
on some other robot. `SoftArmSpec.sphere_coverage_margin` records that the union does
contain a rod of `backbone_radius`, and the containment test measures it.
"""

import os
from xml.sax.saxutils import escape

from src.soft_arm.params import SoftArmSpec, RUNGS

#: A sub-link's mass, spread over the arm. Dynamics are never run, but Drake draws
#: inertia visuals and a zero-mass body produces a degenerate ellipsoid.
_ARM_MASS = 1.0


def _inertia_block(mass, radius):
    """A solid sphere's inertia. Valid numbers, since the geometry is spheres."""
    i = 0.4 * mass * radius * radius
    return (f"<inertial><mass>{mass:.9g}</mass><inertia>"
            f"<ixx>{i:.9g}</ixx><ixy>0</ixy><ixz>0</ixz>"
            f"<iyy>{i:.9g}</iyy><iyz>0</iyz><izz>{i:.9g}</izz>"
            f"</inertia></inertial>")


def RenderSdf(spec: SoftArmSpec) -> str:
    """The model as SDFormat text. Deterministic: same spec, same bytes."""
    per_body = _ARM_MASS / spec.num_bodies
    lines = [
        '<?xml version="1.0"?>',
        "<!-- GENERATED by src/soft_arm/generate_sdf.py from src/soft_arm/params.py.",
        "     Do not edit by hand: regenerate, and a test asserts byte-equality. -->",
        '<sdf version="1.9">',
        f'  <model name="{escape(spec.name)}">',
        "",
        "    <!-- Welded to the world at identity by the scene. That is load-bearing, not",
        "         stylistic: CalibrateFlowFrame compares a WORLD-frame scene pose against",
        "         the flow's BASE-frame pose and requires the offset to be constant, which",
        "         it is only when the base sits at the origin. -->",
        f'    <link name="base">{_inertia_block(per_body, spec.collision_radius)}</link>',
        "",
    ]

    for segment in range(spec.num_segments):
        lines.append(f"    <!-- segment {segment} -->")
        for sub in range(spec.sublinks_per_segment):
            name = f"seg{segment}_sub{sub}"
            lines += [
                f'    <link name="{name}">',
                f"      {_inertia_block(per_body, spec.collision_radius)}",
                f'      <collision name="{name}_collision"><geometry>',
                f"        <sphere><radius>{spec.collision_radius:.9g}</radius></sphere>",
                "      </geometry></collision>",
                f'      <visual name="{name}_visual"><geometry>',
                f"        <sphere><radius>{spec.collision_radius:.9g}</radius></sphere>",
                "      </geometry></visual>",
                "    </link>",
            ]
        lines.append("")

    lines += [
        "    <!-- The tip is one sub-arc past the last sub-link's origin, so it is nobody's",
        "         frame and needs a body of its own: the frame the gripper welds to and the",
        "         frame the flow is conditioned on. It carries a collision sphere as well,",
        "         because without one the final sub-arc of rod -- a whole sub-link length,",
        "         33 mm -- is left outside the sphere union. The containment test measured",
        "         exactly that before this sphere existed.",
        "         It joins the LAST segment's filter group, so it neither collides with the",
        "         segment it caps nor with the one before it. -->",
        f'    <link name="{spec.tip_link_name}">',
        f"      {_inertia_block(per_body, spec.collision_radius)}",
        f'      <collision name="{spec.tip_link_name}_collision"><geometry>',
        f"        <sphere><radius>{spec.collision_radius:.9g}</radius></sphere>",
        "      </geometry></collision>",
        f'      <visual name="{spec.tip_link_name}_visual"><geometry>',
        f"        <sphere><radius>{spec.collision_radius:.9g}</radius></sphere>",
        "      </geometry></visual>",
        "    </link>",
        f'    <frame name="{spec.tip_frame_name}" attached_to="{spec.tip_link_name}"/>',
        "",
        "    <!-- Self-collision is filtered WITHIN a segment and between ADJACENT segments:",
        "         consecutive spheres overlap by construction, which is what makes the union",
        "         a rod rather than a string of beads. Non-adjacent segments stay live, and",
        "         they bind: this arm can curl through itself. -->",
    ]

    for segment in range(spec.num_segments):
        names = [f"seg{segment}_sub{sub}" for sub in range(spec.sublinks_per_segment)]
        if segment == spec.num_segments - 1:
            names.append(spec.tip_link_name)
        members = "".join(f"<drake:member>{name}</drake:member>" for name in names)
        ignored = [f"seg{segment}"]
        if segment + 1 < spec.num_segments:
            ignored.append(f"seg{segment + 1}")
        ignores = "".join(
            f"<drake:ignored_collision_filter_group>{name}"
            f"</drake:ignored_collision_filter_group>" for name in ignored)
        lines.append(f'    <drake:collision_filter_group name="seg{segment}">'
                     f"{members}{ignores}</drake:collision_filter_group>")

    lines += ["  </model>", "</sdf>", ""]
    return "\n".join(lines)


def OutputPath(spec: SoftArmSpec, root: str) -> str:
    return os.path.join(root, "models", spec.name, f"{spec.name}.sdf")


def main():
    from src.utils import RepoDir
    root = RepoDir()
    for spec in RUNGS.values():
        os.makedirs(os.path.join(root, "models", spec.name), exist_ok=True)
    for spec in RUNGS.values():
        path = OutputPath(spec, root)
        with open(path, "w") as handle:
            handle.write(RenderSdf(spec))
        print(f"wrote {os.path.relpath(path, root)}  "
              f"({spec.num_bodies} bodies, {spec.num_plant_positions} positions)")


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.realpath(__file__)))))
    main()
