"""Emit the soft arm's scene YAMLs, hardened and legacy, from one description.

The repo's rigid-arm scenes are a hand-maintained pair -- a legacy file and a hardened
twin defined as "the legacy one minus these removals" -- with a test enforcing the
relation because the two can drift. These are generated from a single function instead, so
the relation holds by construction and the test becomes a check on the generator rather
than on somebody's diff discipline.

The furniture is byte-identical to the iiwa's: the same two tables at [0.4, 0, 0] and
[-0.2, 0, 0], the same four shelf units at the four welds `src/shelf_regions.py` hardcodes.
That is what lets the soft arm reuse the shelf compartment table, the containment
predicate and the acceptance probe without touching any of them.

TWO THINGS THAT ARE NOT COSMETIC.

The arm's base is welded to `world` with NO `X_PC`. `CalibrateFlowFrame` compares a
WORLD-frame scene pose against the flow's BASE-frame pose and requires the offset to be
constant; it is constant only when the base sits at the origin. A plinth would break the
check by the plinth's height -- five orders past the gate -- and would more quietly hand
the network a conditioning pose in the wrong frame, which is the failure that collapsed
the Panda pose task to 10/60. Both rigid arms are welded at the origin for the same
reason, though nothing there said so.

The gripper is filtered against the last segment and the tip sphere. It is welded at the
tip and therefore always inside that sphere; without the filter every configuration would
read as in collision. It is deliberately NOT filtered against the other segments -- a soft
arm really can curl its gripper into its own body, and that is a constraint, not an
artefact.
"""

import os

from src.soft_arm.params import SoftArmSpec, RUNGS

_ARM_URI = "package://combining_kinematics/models/soft_arm/{name}.sdf"
_GRIPPER_URI = ("package://combining_kinematics/models/wsg_finray/"
                "wsg50_110_finray_fingers_box_collision.sdf")
_TABLE_URI = "package://drake_models/manipulation_station/table_wide.sdf"
_SHELF_URI = "package://combining_kinematics/models/assets/shelves.sdf"
_BIN_URI = "package://drake_models/manipulation_station/bin2.sdf"

#: Identical to the rigid arms', and to `src/shelf_regions.py:SHELF_WELDS`.
_TABLES = (("table", (0.4, 0.0, 0.0)), ("table2", (-0.2, 0.0, 0.0)))
_SHELVES = (("shelves", (0.3, 0.55, 0.4), 235.0),
            ("shelves2", (0.3, -0.55, 0.4), 135.0),
            ("shelves3", (-0.45, -0.55, 0.4), 235.0),
            ("shelves4", (-0.45, 0.55, 0.4), 135.0))

#: The gripper's `hand` frame has `between_fingers` at +0.1 m along its own +y, so a
#: quarter turn about x points the grasp straight out along the arm's tangent (+z of the
#: tip frame). The 0.100 m separation that results is the one
#: `tests/test_shelf_placement_screens.py` pins across robots.
_GRIPPER_ROTATION_DEG = (90.0, 0.0, 0.0)


def _model(name, uri):
    return [f"  - add_model:", f"      name: {name}", f"      file: {uri}", ""]


def _weld(parent, child, translation=None, rotation_deg=None):
    lines = ["  - add_weld:", f"      parent: {parent}", f"      child: {child}"]
    if translation is not None or rotation_deg is not None:
        lines.append("      X_PC:")
        if translation is not None:
            lines.append(f"        translation: [{translation[0]}, {translation[1]}, "
                         f"{translation[2]}]")
        if rotation_deg is not None:
            lines.append(f"        rotation: !Rpy {{ deg: [{rotation_deg[0]}, "
                         f"{rotation_deg[1]}, {rotation_deg[2]}] }}")
    lines.append("")
    return lines


def RenderScene(spec: SoftArmSpec, legacy: bool = False) -> str:
    """The scene as a Drake model-directives YAML.

    `legacy` adds the bin the hardened scene is defined as dropping, so the pair stands in
    the same relation as the rigid arms' and the existing screens test applies unchanged.
    """
    variant = ("Legacy variant: carries `binF`, which the hardened twin drops."
               if legacy else
               "Hardened variant of soft_arm/<rung>_collision.yaml: `binF` removed.")
    last = spec.num_segments - 1
    gripper_group = (
        [f"        - finray::hand", "        - finray::left_finger",
         "        - finray::right_finger"]
        + [f"        - {spec.name}::seg{last}_sub{sub}"
           for sub in range(spec.sublinks_per_segment)]
        + [f"        - {spec.name}::{spec.tip_link_name}"])

    lines = [
        f"# GENERATED by src/soft_arm/generate_scenes.py from src/soft_arm/params.py.",
        f"# Do not edit by hand: regenerate, and a test asserts byte-equality.",
        f"# {variant}",
        "# Four shelves, two tables, at the same welds as the rigid arms' scenes, so the",
        "# shelf compartment table and the containment predicate apply unchanged.",
        "directives:",
        "",
        "# The soft arm. Welded at the ORIGIN with no X_PC -- CalibrateFlowFrame compares a",
        "# world-frame scene pose against a base-frame flow pose and needs the offset to be",
        "# constant, which holds only at the origin.",
    ]
    lines += _model(spec.name, _ARM_URI.format(name=spec.name))
    lines += _weld("world", f"{spec.name}::base")

    lines += ["# The same finray gripper the iiwa carries, so `between_fingers` and the",
              "# 0.100 m wrist-to-fingertip separation are literally the same geometry."]
    lines += _model("finray", _GRIPPER_URI)
    lines += _weld(f"{spec.name}::{spec.tip_frame_name}", "finray::hand",
                   rotation_deg=_GRIPPER_ROTATION_DEG)

    lines += [
        "# The gripper sits inside the tip sphere by construction, so it is filtered",
        "# against the last segment. It is NOT filtered against the rest of the arm: a",
        "# soft arm can curl its gripper into its own body, and that is a real constraint.",
        "  - add_collision_filter_group:",
        "      name: gripper_and_tip",
        "      members:",
    ] + gripper_group + [
        "      ignored_collision_filter_groups: [gripper_and_tip]",
        "",
    ]

    if legacy:
        lines += _model("binF", _BIN_URI)
        lines += _weld("world", "binF::bin_base", (0.75, 0, 0), (0.0, 0.0, 0.0))

    for name, translation in _TABLES:
        lines += _model(name, _TABLE_URI)
        lines += _weld("world", f"{name}::table_body", translation)

    for name, translation, yaw in _SHELVES:
        lines += _model(name, _SHELF_URI)
        lines += _weld("world", f"{name}::shelves_body", translation, (0.0, 0.0, yaw))

    return "\n".join(lines).rstrip() + "\n"


def ScenePath(spec: SoftArmSpec, root: str, legacy: bool = False) -> str:
    suffix = "collision" if legacy else "collision_hardened"
    return os.path.join(root, "models", "soft_arm", f"{spec.name}_{suffix}.yaml")


def main():
    from src.utils import RepoDir
    root = RepoDir()
    os.makedirs(os.path.join(root, "models", "soft_arm"), exist_ok=True)
    for spec in RUNGS.values():
        for legacy in (False, True):
            path = ScenePath(spec, root, legacy)
            with open(path, "w") as handle:
                handle.write(RenderScene(spec, legacy))
            print(f"wrote {os.path.relpath(path, root)}")


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.realpath(__file__)))))
    main()
