"""Emit the GVS push-rod arm's scene YAMLs, hardened and legacy, from one description.

The soft PCS arm's generator, applied to this robot: the same two tables, the same four
shelf units at the four welds `src/shelf_regions.py` hardcodes, the same finray gripper at
the same quarter-turn on the tip frame. Keeping the furniture byte-identical across robots
is what lets the shelf compartment table, the containment predicate and the acceptance probe
apply unchanged, and is the comparability rule Thomas set ("a mismatch in setup across
experiments is a landmine").

THE BASE IS WELDED TO `world` WITH NO `X_PC`. `CalibrateFlowFrame` compares a WORLD-frame
scene pose against the flow's BASE-frame pose and requires a constant offset; that holds
only at the origin. SoRoMoX mounts its rod upright at the origin too, so the poses it
reports ARE world poses and nothing here rotates a frame.

The gripper is filtered against the last segment and the tip sphere -- it is welded at the
tip and always inside that sphere -- and deliberately NOT against the other segments: a
continuum arm can curl its gripper into its own body, and that is a constraint, not an
artefact. The first spheres are filtered against the tables because the arm is mounted
THROUGH the table surface at z = 0, exactly as the PCS arm's scene documents.
"""

import os

from src.gvs_arm.params import GvsArmSpec, RUNGS

_ARM_URI = "package://combining_kinematics/models/{name}/{name}.sdf"
_GRIPPER_URI = ("package://combining_kinematics/models/wsg_finray/"
                "wsg50_110_finray_fingers_box_collision.sdf")
_TABLE_URI = "package://drake_models/manipulation_station/table_wide.sdf"
_SHELF_URI = "package://combining_kinematics/models/assets/shelves.sdf"
_BIN_URI = "package://drake_models/manipulation_station/bin2.sdf"

#: Identical to the rigid arms', to the PCS arm's, and to `src/shelf_regions.py:SHELF_WELDS`.
_TABLES = (("table", (0.4, 0.0, 0.0)), ("table2", (-0.2, 0.0, 0.0)))
_SHELVES = (("shelves", (0.3, 0.55, 0.4), 235.0),
            ("shelves2", (0.3, -0.55, 0.4), 135.0),
            ("shelves3", (-0.45, -0.55, 0.4), 235.0),
            ("shelves4", (-0.45, 0.55, 0.4), 135.0))

#: The gripper's `hand` frame has `between_fingers` at +0.1 m along its own +y, so a
#: quarter turn about x points the grasp straight out along the tip frame's +z, which the
#: SDF's tip-frame pose puts along the backbone.
_GRIPPER_ROTATION_DEG = (90.0, 0.0, 0.0)


def _model(name, uri):
    return [f"  - add_model:", f"      name: {name}", f"      file: {uri}", ""]


def _weld(parent, child, translation=None, rotation_deg=None):
    lines = ["  - add_weld:", f"      parent: {parent}", f"      child: {child}"]
    if translation is not None or rotation_deg is not None:
        lines.append("      X_PC:")
        if translation is not None:
            lines.append(f"        translation: [{translation[0]}, {translation[1]}, "
                         f"{translation[2]}]")
        if rotation_deg is not None:
            lines.append(f"        rotation: !Rpy {{ deg: [{rotation_deg[0]}, "
                         f"{rotation_deg[1]}, {rotation_deg[2]}] }}")
    lines.append("")
    return lines


def RenderScene(spec: GvsArmSpec, legacy: bool = False) -> str:
    """The scene as a Drake model-directives YAML; `legacy` adds the bin the hardened one drops."""
    variant = ("Legacy variant: carries `binF`, which the hardened twin drops."
               if legacy else
               "Hardened variant of gvs_arm/<rung>_collision.yaml: `binF` removed.")
    last = spec.num_segments - 1
    gripper_group = (
        [f"        - finray::hand", "        - finray::left_finger",
         "        - finray::right_finger"]
        + [f"        - {spec.name}::seg{last}_sub{sub}"
           for sub in range(spec.sublinks_per_segment)]
        + [f"        - {spec.name}::{spec.tip_link_name}"])

    lines = [
        f"# GENERATED by src/gvs_arm/generate_scenes.py from src/gvs_arm/params.py.",
        f"# Do not edit by hand: regenerate, and a test asserts byte-equality.",
        f"# {variant}",
        "# Four shelves, two tables, at the same welds as every other robot's scenes, so the",
        "# shelf compartment table and the containment predicate apply unchanged.",
        "directives:",
        "",
        "# The GVS push-rod arm. Welded at the ORIGIN with no X_PC -- CalibrateFlowFrame",
        "# compares a world-frame scene pose against a base-frame flow pose and needs the",
        "# offset to be constant, which holds only at the origin.",
    ]
    lines += _model(spec.name, _ARM_URI.format(name=spec.name))
    lines += _weld("world", f"{spec.name}::base")

    lines += ["# The same finray gripper every other robot carries, so `between_fingers` and",
              "# the 0.100 m wrist-to-fingertip separation are literally the same geometry."]
    lines += _model("finray", _GRIPPER_URI)
    lines += _weld(f"{spec.name}::{spec.tip_frame_name}", "finray::hand",
                   rotation_deg=_GRIPPER_ROTATION_DEG)

    lines += [
        "# The gripper sits inside the tip sphere by construction, so it is filtered",
        "# against the last segment. It is NOT filtered against the rest of the arm: a",
        "# continuum arm can curl its gripper into its own body, a real constraint.",
        "  - add_collision_filter_group:",
        "      name: gripper_and_tip",
        "      members:",
    ] + gripper_group + [
        "      ignored_collision_filter_groups: [gripper_and_tip]",
        "",
    ]

    if legacy:
        lines += _model("binF", _BIN_URI)
        lines += _weld("world", "binF::bin_base", (0.75, 0, 0), (0.0, 0.0, 0.0))

    for name, translation in _TABLES:
        lines += _model(name, _TABLE_URI)
        lines += _weld("world", f"{name}::table_body", translation)

    for name, translation, yaw in _SHELVES:
        lines += _model(name, _SHELF_URI)
        lines += _weld("world", f"{name}::shelves_body", translation, (0.0, 0.0, yaw))

    ## AFTER the tables: directives are processed in order, and a filter group naming a
    ## body that has not been added yet fails at parse time.
    lines += [
        "# The arm is mounted THROUGH the table surface at z = 0, so its first collision",
        "# sphere(s) are centred inside the table. The rigid arms get this for free (a",
        "# welded base and Drake never checks two ANCHORED geometries); a floating sub-link",
        "# does not, and without this filter every configuration reads as in collision.",
        "# Only the spheres whose centres sit within their own radius of z = 0, derived from",
        "# the spec so a change to the discretization cannot leave one unfiltered.",
        "  - add_collision_filter_group:",
        "      name: arm_base_and_tables",
        "      members:",
    ] + [f"        - {spec.name}::seg0_sub{sub}"
         for sub in range(spec.sublinks_below_table())] + [
        "        - table::table_body",
        "        - table2::table_body",
        "      ignored_collision_filter_groups: [arm_base_and_tables]",
    ]

    return "\n".join(lines).rstrip() + "\n"


def ScenePath(spec: GvsArmSpec, root: str, legacy: bool = False) -> str:
    suffix = "collision" if legacy else "collision_hardened"
    return os.path.join(root, "models", spec.name, f"{spec.name}_{suffix}.yaml")


def main():
    from src.utils import RepoDir
    root = RepoDir()
    for spec in RUNGS.values():
        os.makedirs(os.path.join(root, "models", spec.name), exist_ok=True)
        for legacy in (False, True):
            path = ScenePath(spec, root, legacy)
            with open(path, "w") as handle:
                handle.write(RenderScene(spec, legacy))
            print(f"wrote {os.path.relpath(path, root)}")


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.realpath(__file__)))))
    main()
