"""Emit the GVS push-rod arm's Drake model from `params.py`, so the two cannot drift.

The generated file is committed alongside this generator, and a test regenerates it and
asserts byte-equality -- the discipline the soft PCS arm and the hardened scene YAMLs already
run on ("regenerate; do not hand-edit the two out of step").

Same construction as the soft PCS arm's model, for the same measured reasons: one quaternion
FLOATING BODY per collision sub-link (no gimbal lock, +-inf limits so a sampler over plant
limits fails loudly), SPHERES for collision geometry (Drake's proximity engine hangs on this
model's capsules), the union of spheres DECLARED to be the robot's geometry rather than an
approximation of a swept rod. Two things differ:

  * every sphere follows the TAPER -- its radius is `collision_radius_ratio` times the local
    backbone radius at that body's arc length, so the union is a cone of spheres rather than
    a cylinder of them, and the containment test measures it on the tapered rod's surface;
  * the tip FRAME carries a pose: `R_y(+90 deg)` relative to the tip body, because SoRoMoX's
    backbone is its local x-axis and the frame the gripper welds to and the flow conditions
    on must have its z-axis along the backbone, as the PCS arm's does.

The sub-link poses are written into the plant from outside (`model.py`), which is the only
sense in which this file describes the robot: it is the collision discretization of
whatever configuration SoRoMoX's equilibrium reaches, not a description of any degree of
freedom.
"""

import os
from xml.sax.saxutils import escape

from src.gvs_arm.params import GvsArmSpec, RUNGS

#: The tip frame relative to the tip body, as `params.py`/`model.py` define it. Kept as a
#: literal here so the generated file is bit-stable and does not depend on `math.pi`'s repr.
_TIP_FRAME_PITCH = "1.5707963267948966"

#: A body's mass, spread over the arm. Dynamics are never run, but Drake draws inertia
#: visuals and a zero-mass body produces a degenerate ellipsoid.
_ARM_MASS = 1.0


def _inertia_block(mass, radius):
    """A solid sphere's inertia. Valid numbers, since the geometry is spheres."""
    i = 0.4 * mass * radius * radius
    return (f"<inertial><mass>{mass:.9g}</mass><inertia>"
            f"<ixx>{i:.9g}</ixx><ixy>0</ixy><ixz>0</ixz>"
            f"<iyy>{i:.9g}</iyy><iyz>0</iyz><izz>{i:.9g}</izz>"
            f"</inertia></inertial>")


def _sphere_body(name, radius, per_body):
    return [
        f'    <link name="{name}">',
        f"      {_inertia_block(per_body, radius)}",
        f'      <collision name="{name}_collision"><geometry>',
        f"        <sphere><radius>{radius:.9g}</radius></sphere>",
        "      </geometry></collision>",
        f'      <visual name="{name}_visual"><geometry>',
        f"        <sphere><radius>{radius:.9g}</radius></sphere>",
        "      </geometry></visual>",
        "    </link>",
    ]


def RenderSdf(spec: GvsArmSpec) -> str:
    """The model as SDFormat text. Deterministic: same spec, same bytes."""
    per_body = _ARM_MASS / spec.num_bodies
    radii = spec.body_radii()
    lines = [
        '<?xml version="1.0"?>',
        "<!-- GENERATED by src/gvs_arm/generate_sdf.py from src/gvs_arm/params.py.",
        "     Do not edit by hand: regenerate, and a test asserts byte-equality. -->",
        '<sdf version="1.9">',
        f'  <model name="{escape(spec.name)}">',
        "",
        "    <!-- Welded to the world at identity by the scene. That is load-bearing, not",
        "         stylistic: CalibrateFlowFrame compares a WORLD-frame scene pose against",
        "         the flow's BASE-frame pose and requires the offset to be constant, which",
        "         it is only when the base sits at the origin. -->",
        f'    <link name="base">{_inertia_block(per_body, radii[0])}</link>',
        "",
    ]

    index = 0
    for segment in range(spec.num_segments):
        lines.append(f"    <!-- segment {segment}: the sphere radius follows the taper -->")
        for sub in range(spec.sublinks_per_segment):
            lines += _sphere_body(f"seg{segment}_sub{sub}", radii[index], per_body)
            index += 1
        lines.append("")

    lines += [
        "    <!-- The tip is one sub-arc past the last sub-link's origin, so it is nobody's",
        "         frame and needs a body of its own: the frame the gripper welds to and the",
        "         frame the flow is conditioned on. Its sphere closes the union over the",
        "         final sub-arc of rod. It joins the LAST segment's filter group, so it",
        "         neither collides with the segment it caps nor with the one before it. -->",
    ] + _sphere_body(spec.tip_link_name, radii[-1], per_body) + [
        "    <!-- SoRoMoX's backbone is its local x-axis, so the tip BODY's x points along",
        "         the rod; the tip FRAME is pitched by +90 degrees so that its z does, which",
        "         is the convention the gripper weld and the flow's conditioning pose use",
        "         on every other robot here. -->",
        f'    <frame name="{spec.tip_frame_name}" attached_to="{spec.tip_link_name}">',
        f'      <pose relative_to="{spec.tip_link_name}">0 0 0 0 {_TIP_FRAME_PITCH} 0</pose>',
        "    </frame>",
        "",
        "    <!-- Self-collision is filtered WITHIN a segment and between ADJACENT segments:",
        "         consecutive spheres overlap by construction, which is what makes the union",
        "         a rod rather than a string of beads. Non-adjacent segments stay live, and",
        "         they bind: this arm can curl through itself. -->",
    ]

    for segment in range(spec.num_segments):
        names = [f"seg{segment}_sub{sub}" for sub in range(spec.sublinks_per_segment)]
        if segment == spec.num_segments - 1:
            names.append(spec.tip_link_name)
        members = "".join(f"<drake:member>{name}</drake:member>" for name in names)
        ignored = [f"seg{segment}"]
        if segment + 1 < spec.num_segments:
            ignored.append(f"seg{segment + 1}")
        ignores = "".join(
            f"<drake:ignored_collision_filter_group>{name}"
            f"</drake:ignored_collision_filter_group>" for name in ignored)
        lines.append(f'    <drake:collision_filter_group name="seg{segment}">'
                     f"{members}{ignores}</drake:collision_filter_group>")

    lines += ["  </model>", "</sdf>", ""]
    return "\n".join(lines)


def OutputPath(spec: GvsArmSpec, root: str) -> str:
    return os.path.join(root, "models", spec.name, f"{spec.name}.sdf")


def main():
    from src.utils import RepoDir
    root = RepoDir()
    for spec in RUNGS.values():
        os.makedirs(os.path.join(root, "models", spec.name), exist_ok=True)
        path = OutputPath(spec, root)
        with open(path, "w") as handle:
            handle.write(RenderSdf(spec))
        print(f"wrote {os.path.relpath(path, root)}  "
              f"({spec.num_bodies} bodies, {spec.num_plant_positions} positions)")


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(
        os.path.realpath(__file__)))))
    main()
