#!/bin/bash
# Submit a benchmark manifest as a DEPENDENCY-CHAINABLE job, so a measurement can be
# interleaved between training rungs of the ladder.
#
# ============================ STANDING REMINDER ============================
# If even REMOTELY unsure about a SuperCloud action, STOP and ask Thomas.
# ===========================================================================
#
# Usage:
#   DEPENDENCY=afterany:5560250 bash cluster/submit_bench.sh manifest_stageLADDERTRI.txt 4
#
# WHY THIS EXISTS, separately from cluster/submit.sh. submit.sh uses LLsub's flag mode,
# which cannot express --dependency. The ladder occupies all 4 volta nodes continuously
# (each rung is a 4-node job and afterany starts the next the instant one ends), so there
# is NO idle window a benchmark could drift into -- it has to be an explicit link in the
# chain or it never runs. Generating our own #SBATCH launcher is the only way to say that.
#
# The caller is responsible for re-pointing the NEXT training rung at this job, e.g.
#   scontrol update jobid=<next_rung> Dependency=afterany:<this_job>
# otherwise the rung still fires off the previous training job and runs concurrently,
# which would both contend for the cap and corrupt the wall-clock-capped measurement.
#
# PROCS comes from the calibration, not a guess: the benchmark is wall-clock capped, so
# concurrent workers that contend for CPU change WHAT IS MEASURED (40 workers/node cost
# 44% of the per-cell iteration count; 8 cost 8%). Every arm in one manifest sees the same
# contention, so a within-run comparison stays sound -- but do not compare across runs that
# used different PROCS.
set -uo pipefail
source "$(dirname "$0")/ssh_common.sh"

MANIFEST="${1:?usage: submit_bench.sh <manifest-basename> [n_jobs]}"
NJOBS="${2:-4}"
PROCS="${PROCS:-8}"
WALL="${WALL:-04:00:00}"
PARTITION="${PARTITION:-xeon-g6-volta}"
DEPENDENCY="${DEPENDENCY:-}"
DEP_DIRECTIVE="${DEPENDENCY:+1}"
EXCLUDE_NODES="${EXCLUDE_NODES:-}"
EXC_DIRECTIVE="${EXCLUDE_NODES:+1}"

LOCAL="$(_sc_repo_root)/cluster/$MANIFEST"
[ -f "$LOCAL" ] || { echo "no such local manifest: $LOCAL" >&2; exit 1; }
echo "local:  $MANIFEST ($(grep -vc '^#' "$LOCAL") items)"

## Refuse rather than launch jobs that cannot work -- a manifest that is not on the cluster
## produces jobs that start, find nothing, and exit silently, which reads as "submitted and
## produced nothing" only much later.
sc_run "test -f ~/$SC_ROOT/repo/cluster/$MANIFEST" || {
    echo "REFUSING: cluster/$MANIFEST is not staged. Run cluster/stage_code.sh first." >&2
    exit 2
}

## Refuse rather than measure a checkpoint that does not exist. A benchmark against a
## missing --checkpoint does not fail fast: the workers start, construct a program, and
## die per cell, so four jobs burned 16 minutes each before anyone noticed. This happened
## for real on 2026-09-09, when a path bug in the in-job export left iiwa14_n6 trained but
## unexported and the interleaved benchmark fired anyway.
## A CHAINED submission is the exception: its checkpoint is produced by the very job it
## depends on, so it cannot exist yet. Pre-queuing those is the whole point -- it is what
## keeps the allocation busy without a human at each rung transition. So the check moves
## into the launcher (below), where it runs at JOB START and still fails in seconds rather
## than per cell. Unchained submissions keep the submit-time check, which is strictly
## better feedback when it can be given.
CKPTS=$(grep -o -- '--checkpoint[= ][^ ]*' "$LOCAL" | sed 's/^--checkpoint[= ]//' | sort -u)
if [ -z "$DEPENDENCY" ]; then
    for c in $CKPTS; do
        sc_run "test -f ~/$SC_ROOT/repo/$c" || {
            echo "REFUSING: $MANIFEST references a checkpoint that is not on the cluster:" >&2
            echo "  $c" >&2
            echo "Export the run first (cluster/submit_export.sh), then resubmit." >&2
            exit 3
        }
    done
else
    echo "chained submission: checkpoint existence is checked at job start, not now"
fi

LAUNCH_R="\$HOME/$SC_ROOT/results/_bench_launch_${MANIFEST%.txt}.sh"
echo "Submitting $NJOBS job(s): PROCS=$PROCS PARTITION=$PARTITION DEP='${DEPENDENCY:-none}'"

sc_run "cat > $LAUNCH_R && chmod +x $LAUNCH_R" <<LAUNCH
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH --gres=gpu:volta:2
#SBATCH --partition=$PARTITION
#SBATCH --exclusive
#SBATCH --time=$WALL
#SBATCH --job-name=lik_bench_${MANIFEST%.txt}${DEP_DIRECTIVE:+
#SBATCH --dependency=$DEPENDENCY}${EXC_DIRECTIVE:+
#SBATCH --exclude=$EXCLUDE_NODES}
#SBATCH --output=../results/bench_${MANIFEST%.txt}.log-%j
# Generated by cluster/submit_bench.sh $(date -Is) -- do not edit; resubmit instead.
cd "\$HOME/$SC_ROOT/repo" || exit 2
## Fail fast on a missing checkpoint rather than per cell. See submit_bench.sh.
for c in $CKPTS; do
    [ -f "\$c" ] || { echo "FATAL: checkpoint missing at job start: \$c" >&2; exit 3; }
done
MANIFEST=cluster/$MANIFEST PROCS=$PROCS "\$HOME/$SC_ROOT/repo/cluster/run_items.sh"
LAUNCH

for i in $(seq 1 "$NJOBS"); do
    sc_run "cd ~/$SC_ROOT/repo && LLsub $LAUNCH_R" 2>&1 | grep -E "Submitted batch job"
done
