#!/bin/bash
# Submit (or resume) the iiwa14 retraining job -- one command, idempotent.
#
# ============================ STANDING REMINDER ============================
# If even REMOTELY unsure about a SuperCloud action, STOP and ask Thomas.
# ===========================================================================
#
# Usage:
#   bash cluster/submit_train.sh <run_name> [nnodes] [walltime] [-- extra train args]
# e.g.
#   bash cluster/submit_train.sh iiwa14_ddp_r1 4 96:00:00
#   bash cluster/submit_train.sh smoke2n 2 00:20:00 -- --max_steps=200 --eval_every=100 \
#       --val_set_size=20 --checkpoint_every=100 --pole_eval_n=500 --disable_wandb
#
# WHY NOT LLsub TRIPLE MODE: "[N,1,40]" generates a Slurm job ARRAY of N
# independent single-node jobs (llsub_batch.py: --array=1-N), so the nodes never
# share an allocation and the c10d rendezvous cannot form; its wrapper also execs
# the payload directly (needs the exec bit) and ends in a bare `wait`, which
# swallows every payload exit code (our first smoke "COMPLETED 0:0" in 1 s with
# empty logs on a chmod-less script). Instead we generate a launcher with
# #SBATCH directives -- LLsub's supported directives path
# (_submit_sbatch_with_directives) -- giving ONE job spanning N nodes, with
# `srun` fanning train_iiwa.sh out once per node inside the allocation, so
# SLURM_JOB_NODELIST covers all nodes (MASTER_ADDR is right), SLURM_NODEID is
# the node rank, and srun --kill-on-bad-exit propagates real exit codes.
# NOTE: in directives mode LLsub DROPS -g/-q/-T/-J, so every resource lives in
# the directives below. The launcher is written to $RUN_DIR/launch.sh and kept.
#
# Refuses if a lik_train job for ANY run is already RUNNING or PENDING: a second
# job on the same RUN_DIR would race its checkpoints (with <4 nodes in use it
# would START, not queue), and the volta group cap is shared with Thomas's other
# work. Scoped to this project's own job names -- the account is shared across
# projects (cluster/README, guard-scoping lesson).
set -uo pipefail
source "$(dirname "$0")/ssh_common.sh"

RUN_NAME="${1:?usage: submit_train.sh <run_name> [nnodes] [walltime] [-- extra args]}"
NNODES="${2:-4}"
WALL="${3:-96:00:00}"
PARTITION="${PARTITION:-xeon-g6-volta}"   # PARTITION=debug-gpu for smoke-sized runs ONLY
GPUS_PER_NODE="${GPUS_PER_NODE:-2}"
BATCH="${BATCH:-256}"
shift $(( $# > 3 ? 3 : $# ))
[ "${1:-}" = "--" ] && shift
EXTRA_ARGS="$*"

LIVE=$(sc_run 'LLstat 2>/dev/null | grep -c "lik_train"' 2>/dev/null | tr -dc '0-9')
if [ -n "${LIVE:-}" ] && [ "${LIVE:-0}" -gt 0 ]; then
    echo "REFUSING: $LIVE lik_train job(s) already RUNNING/PENDING." >&2
    echo "Two jobs on one RUN_DIR race the checkpoints. LLkill the old one or wait." >&2
    exit 3
fi

## The payload is exec'd by srun, so the exec bit is load-bearing (rsync -a
## preserves it from the local checkout; this catches a bad restage).
sc_run "test -x ~/$SC_ROOT/repo/cluster/train_iiwa.sh" || {
    echo "REFUSING: train_iiwa.sh on the cluster is not executable -- restage first." >&2
    exit 4
}

RUN_DIR_R="\$HOME/$SC_ROOT/results/train/$RUN_NAME"    # expanded remotely

echo "Submitting: RUN_NAME=$RUN_NAME NNODES=$NNODES WALL=$WALL PARTITION=$PARTITION EXTRA='$EXTRA_ARGS'"
sc_run "mkdir -p $RUN_DIR_R && cat > $RUN_DIR_R/launch.sh && chmod +x $RUN_DIR_R/launch.sh" <<LAUNCH
#!/bin/bash
#SBATCH --nodes=$NNODES
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH --gres=gpu:volta:2
#SBATCH --partition=$PARTITION
#SBATCH --exclusive
#SBATCH --time=$WALL
#SBATCH --job-name=lik_train_$RUN_NAME
#SBATCH --output=../results/train/$RUN_NAME/launch.log-%j
# Generated by cluster/submit_train.sh $(date -Is) -- do not edit; resubmit instead.
srun --ntasks-per-node=1 --kill-on-bad-exit=1 "\$HOME/$SC_ROOT/repo/cluster/train_iiwa.sh"
LAUNCH

sc_run "cd ~/$SC_ROOT/repo && \
  RUN_NAME='$RUN_NAME' NNODES=$NNODES GPUS_PER_NODE=$GPUS_PER_NODE BATCH=$BATCH \
  TRAIN_EXTRA_ARGS='$EXTRA_ARGS' \
  LLsub $RUN_DIR_R/launch.sh"
