#!/bin/bash
# Submit an export+screen job for one finished (or soon-to-finish) training run, optionally
# chained behind another job.
#
# ============================ STANDING REMINDER ============================
# If even REMOTELY unsure about a SuperCloud action, STOP and ask Thomas.
# ===========================================================================
#
# Usage:
#   bash cluster/submit_export.sh <run_name> <robot> [final_step]
#   DEPENDENCY=afterany:5559773 bash cluster/submit_export.sh iiwa14_n6 iiwa14
#
# Normally you do NOT need this: train_flow.sh exports and screens inline on node 0 when
# training succeeds, which is what lets the ladder chain unattended. This exists for the
# cases inline export cannot cover -- a run that started before that was added, a run whose
# training exited non-zero but left usable checkpoints, or a re-screen after a metric change.
#
# It generates its own #SBATCH launcher rather than using LLsub's flag mode, because that
# mode cannot express --dependency, which is the whole point of chaining.
#
# Defaults to xeon-p8 so exports NEVER compete with training for the 4-node volta cap. If
# xeon-p8 is busy with another of Thomas's projects the job simply waits, which is harmless:
# nothing in the training chain depends on an export having finished.
set -uo pipefail
source "$(dirname "$0")/ssh_common.sh"

RUN_NAME="${1:?usage: submit_export.sh <run_name> <robot> [final_step]}"
ROBOT="${2:?usage: submit_export.sh <run_name> <robot> [final_step]}"
FINAL_STEP="${3:-620000}"
PARTITION="${PARTITION:-xeon-p8}"
WALL="${WALL:-02:00:00}"
CPUS="${CPUS:-48}"
SCREEN_N="${SCREEN_N:-20000}"
DEPENDENCY="${DEPENDENCY:-}"
DEP_DIRECTIVE="${DEPENDENCY:+1}"

RUN_DIR_R="\$HOME/$SC_ROOT/results/train/$RUN_NAME"

echo "Submitting export: RUN_NAME=$RUN_NAME ROBOT=$ROBOT FINAL_STEP=$FINAL_STEP" \
     "PARTITION=$PARTITION DEPENDENCY='${DEPENDENCY:-none}'"

sc_run "mkdir -p $RUN_DIR_R && cat > $RUN_DIR_R/export_launch.sh && chmod +x $RUN_DIR_R/export_launch.sh" <<LAUNCH
#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=$CPUS
#SBATCH --partition=$PARTITION
#SBATCH --time=$WALL
#SBATCH --job-name=lik_export_$RUN_NAME${DEP_DIRECTIVE:+
#SBATCH --dependency=$DEPENDENCY}
#SBATCH --output=../results/train/$RUN_NAME/export.log-%j
# Generated by cluster/submit_export.sh $(date -Is) -- do not edit; resubmit instead.
RUN_NAME='$RUN_NAME' ROBOT='$ROBOT' FINAL_STEP='$FINAL_STEP' SCREEN_N='$SCREEN_N' \\
    "\$HOME/$SC_ROOT/repo/cluster/export_and_screen_job.sh"
LAUNCH

sc_run "cd ~/$SC_ROOT/repo && LLsub $RUN_DIR_R/export_launch.sh"
