"""Emit both scene YAMLs for every `helix7` rung, from one description.

The hardened scene is defined as its legacy twin minus `binF`, and
`tests/test_shelf_placement_screens.py` enforces exactly that relation across the whole
tree. On the rigid arms the two files are hand-maintained and the test catches them drifting
apart; here they come out of one description, so the relation holds by construction and the
test becomes a check on this generator instead. That is strictly better, and it is why this
file exists rather than two YAMLs in the repository.

Everything except the arm is shared with the record's robots by URI -- the finray gripper,
the two tables, the four shelves at the welds `src/shelf_regions.py` hardcodes, and the bin
the hardened variant drops. That sharing is the whole point: it is what lets the compartment
table, the containment predicate, the acceptance probe and `FloatingMugScreen` apply to this
robot untouched, and what makes a row here comparable with a row of the record's.

TWO THINGS THAT ARE NOT COSMETIC.

The base is welded to the world with NO `X_PC`. `CalibrateFlowFrame` compares a WORLD-frame
scene pose against the flow's BASE-frame forward kinematics and requires the offset to be
constant; that holds only at `X_W_base = I`. Both rigid arms are welded at the origin, which
is why the check has always passed, though nothing said so. A plinth would break it by the
plinth's height, and would more quietly hand the network a conditioning pose in the wrong
frame -- the failure that once collapsed the Panda pose task to 10/60.

The gripper is welded so `between_fingers` sits 0.200 m along the flange's own axis: 0.100 m
to the end of the flange barrel, then the finray's own 0.100 m from `hand` to
`between_fingers`. That second step is the SAME physical step on all four robots because it
is inside the finray model, which is what lets `ContainmentPose`'s `wrist` and `fingertips`
points mean the same thing here as on the record's rows.
"""

import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../")))

from src.helix_arm.params import GRIPPER_MOUNT_Z, SPECS, HelixArmSpec
from src.shelf_regions import SHELF_WELDS

_FINRAY = ("package://combining_kinematics/models/wsg_finray/"
           "wsg50_110_finray_fingers_box_collision.sdf")
_TABLE = "package://drake_models/manipulation_station/table_wide.sdf"
_SHELF = "package://combining_kinematics/models/assets/shelves.sdf"
_BIN = "package://drake_models/manipulation_station/bin2.sdf"

#: Where the gripper mounts on the flange, and how it is turned. The rotation is the iiwa's,
#: `Rpy deg [90, 0, 90]`, which maps the finray's `hand` +y -- the axis `between_fingers`
#: lies along -- onto the flange's +z. Copying the iiwa rather than the Panda is deliberate:
#: the Panda's weld carries an extra 45 degrees for its own flange keying, which this arm
#: does not have.
_GRIPPER_ROTATION_DEG = (90.0, 0.0, 90.0)

_TABLES = (("table", (0.4, 0.0, 0.0)), ("table2", (-0.2, 0.0, 0.0)))


def _model(name, uri, indent="  "):
    return (f"{indent}- add_model:\n"
            f"{indent}    name: {name}\n"
            f"{indent}    file: {uri}\n")


def _weld(parent, child, translation=None, rotation_deg=None, indent="  "):
    out = (f"{indent}- add_weld:\n"
           f"{indent}    parent: {parent}\n"
           f"{indent}    child: {child}\n")
    if translation is None and rotation_deg is None:
        return out
    out += f"{indent}    X_PC:\n"
    if translation is not None:
        x, y, z = translation
        out += f"{indent}      translation: [{x}, {y}, {z}]\n"
    if rotation_deg is not None:
        r, p, yaw = rotation_deg
        out += f"{indent}      rotation: !Rpy {{ deg: [{r}, {p}, {yaw}] }}\n"
    return out


def RenderScene(spec: HelixArmSpec, legacy: bool = False) -> str:
    """The scene directives. `legacy` keeps `binF`; the hardened variant drops it."""
    arm = spec.name
    uri = f"package://combining_kinematics/models/{arm}/{arm}.sdf"
    header = (
        f"# GENERATED by src/helix_arm/generate_scenes.py. Do not edit: a test asserts this\n"
        f"# file is byte-exactly what the generator emits, and the hardened/legacy relation\n"
        f"# holds by construction rather than by diff discipline.\n")
    if not legacy:
        header += (
            f"# Hardened variant of {arm}_collision.yaml: `binF` removed.\n"
            f"# Four shelves, two tables, no bin -- everything else is byte-identical to\n"
            f"# that file. This scene never had decorative mugs, as the Panda's never did,\n"
            f"# so the bin is the only thing hardening removes.\n")
    body = header + "directives:\n\n"

    body += f"# The arm, welded at the world ORIGIN -- see the module docstring.\n"
    body += _model(arm, uri)
    body += "\n" + _weld("world", f"{arm}::{spec.base_link}") + "\n"

    body += _model("finray", _FINRAY)
    body += "\n" + _weld(f"{arm}::{spec.flange_link}", "finray::hand",
                         translation=(0, 0, GRIPPER_MOUNT_Z),
                         rotation_deg=_GRIPPER_ROTATION_DEG) + "\n"

    if legacy:
        body += _model("binF", _BIN)
        body += "\n" + _weld("world", "binF::bin_base",
                             translation=(0.75, 0, 0),
                             rotation_deg=(0.0, 0.0, 0.0)) + "\n"

    for name, translation in _TABLES:
        body += _model(name, _TABLE)
        body += "\n" + _weld("world", f"{name}::table_body", translation=translation) + "\n"

    ## The shelf welds come from src/shelf_regions.py rather than being written out here,
    ## so the compartment table and the scene cannot disagree about where the shelves are.
    ## That drift is exactly what tests/test_shelf_placement_screens.py exists to catch on
    ## the hand-written scenes.
    for name, tx, ty, tz, yaw in SHELF_WELDS:
        body += _model(name, _SHELF)
        body += "\n" + _weld("world", f"{name}::shelves_body",
                             translation=(tx, ty, tz),
                             rotation_deg=(0.0, 0.0, yaw)) + "\n"
    return body


def ScenePath(spec: HelixArmSpec, root: str, legacy: bool = False) -> str:
    suffix = "collision" if legacy else "collision_hardened"
    return os.path.join(root, "models", spec.name, f"{spec.name}_{suffix}.yaml")


def main():
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../"))
    for spec in SPECS.values():
        for legacy in (True, False):
            path = ScenePath(spec, root, legacy)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w") as f:
                f.write(RenderScene(spec, legacy))
            print(f"wrote {os.path.relpath(path, root)}")


if __name__ == "__main__":
    main()
